In [71]:
import pandas as pd
import numpy as np

In [72]:
# Load Model
root_df = pd.read_csv("./data/data.csv")
root_df

Intent                                           Message
0           Greeting                                                Oi
1           Greeting                                               Olá
2           Greeting                                               Ola
3           Greeting                                           Bom dia
4           Greeting                                         Boa tarde
5           Greeting                                         Boa noite
6            Payment      Estou com dificuldades em pagar meus boletos
7            Payment         Não consigo pagar o boleto da mensalidade
8            Payment        Minha fatura esta atrasada, como procedo ?
9            Payment           Não estou achando a aba de mensalidades
10           Payment   Aonde consulto minhas parcelas de mensalidade ?
11  PasswordRecovery                               Esqueci minha senha
12  PasswordRecovery                 Gostaria de recuperar minha senha
13  PasswordRecovery                               Não sei minha senha
14  PasswordRecovery                     Perdi a minha chave de acesso
15  PasswordRecovery            Como faço para recuperar minha senha ?
16           Absence                         Como vejo minhas faltas ?
17           Absence             Quantas faltas precisa pra reprovar ?
18           Absence   Onde envio o atestado para abonar minha falta ?
19           Absence                        É possível abonar faltas ?
20           GoodBye                                             Adeus
21           GoodBye                                             Tchau
22           GoodBye                               Estou saindo, adeus
23           GoodBye                                     Até a próxima
24           GoodBye                               Adeus, estou saindo
25   GoodByeGreatful                             Muito obrigado, tchau
26   GoodByeGreatful                               Ajudou muito, adeus
27   GoodByeGreatful                        Obrigado pela ajuda, tchau
28  GreetingQuestion                                  Como voce esta ?
29  GreetingQuestion                               Tudo bem com voce ?
30  GreetingQuestion                                   Olá, como vai ?
31  GreetingQuestion                                 Eai, tudo certo ?
32              Joke                                   Conte uma piada
33              Joke                                 fala uma piada ai
34              Joke                                       Me faça rir
35              Joke  estou para baixo, consegue me tirar um sorriso ?
36              Joke                                    Diga uma piada

In [73]:
# SkLearn Imports
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import make_pipeline

from sklearn.feature_selection import SelectKBest, chi2

In [74]:
# Vectorizing X

st_words = pd.read_csv("./stop-words.txt").squeeze().tolist()

vec = CountVectorizer(lowercase=True, binary=True, stop_words=st_words)
X = vec.fit_transform(raw_documents=root_df["Message"]).toarray()

X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
# Enconding Y

le = LabelEncoder()
Y = le.fit_transform(root_df["Intent"])

Y

array([3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 2, 2, 2, 4, 4, 4, 4, 5, 5, 5, 5, 5])

In [76]:
# Select Most Relevant Columns

KBest = SelectKBest(chi2, k=6)

X = KBest.fit_transform(X, Y)
X

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], 

In [77]:
model = make_pipeline(vec, MultinomialNB())
model.fit(root_df["Message"], Y)


Pipeline(steps=[('countvectorizer',
                 CountVectorizer(binary=True,
                                 stop_words=['ao', 'aos', 'aquela', 'aquelas',
                                             'aquele', 'aqueles', 'aquilo',
                                             'as', 'até', 'com', 'como', 'da',
                                             'das', 'de', 'dela', 'delas',
                                             'dele', 'deles', 'depois', 'do',
                                             'dos', 'e', 'ela', 'elas', 'ele',
                                             'eles', 'em', 'entre', 'era',
                                             'eram', ...])),
                ('multinomialnb', MultinomialNB())])

In [78]:
# Tests

new_message = [input()]

predict = model.predict(new_message)

print("Predict: " + le.inverse_transform(predict)[0])
print(model.predict_proba(new_message))

Predict: Greeting
[[0.08843814 0.12233943 0.07340366 0.28598828 0.09532943 0.11327725
  0.11327725 0.10794656]]


In [79]:
import joblib

joblib.dump(model, "./dump/model.sav")
joblib.dump(le, "./dump/encoder.sav")

['./dump/encoder.sav']